default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  # adapter: mysql2
  # encoding: utf8
  # reconnect: false
  # database: blockchain
  # pool: 5
  # username: root
  # password: 12345678
